/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import beans.Manager;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class admin_Student extends javax.swing.JFrame {

    /**
     * Creates new form admin_Student
     */
    ArrayList<beans.Student> studentList;
    int index;

    public admin_Student() {
        initComponents();
        this.setLocationRelativeTo(null);

        index = 0;
        System.out.println(1111);
        studentList = Manager.getAllStudents();

        if (!studentList.isEmpty()) {
            setData(studentList.get(0));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        next_Btn = new javax.swing.JButton();
        st_Type = new javax.swing.JComboBox();
        st_Specilize = new javax.swing.JComboBox();
        st_level = new javax.swing.JComboBox();
        st_Sc_Degree = new javax.swing.JComboBox();
        st_Name = new javax.swing.JTextField();
        st_Id = new javax.swing.JTextField();
        add_Btn = new javax.swing.JButton();
        prev_Btn = new javax.swing.JButton();
        st_Semister = new javax.swing.JComboBox();
        st_Email = new javax.swing.JTextField();
        Email1 = new javax.swing.JLabel();
        st_Pass = new javax.swing.JTextField();
        homeBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Name");

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(51, 0, 204));
        Email.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText(" Degree");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setText("Study Type");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 204));
        jLabel7.setText("Level");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 204));
        jLabel8.setText("Semister");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 204));
        jLabel9.setText("Specialization");

        next_Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        next_Btn.setForeground(new java.awt.Color(51, 0, 204));
        next_Btn.setText(">>");
        next_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        next_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_BtnActionPerformed(evt);
            }
        });

        st_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Affiliate" }));

        st_Specilize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Maths", "Chemistery" }));
        st_Specilize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_SpecilizeActionPerformed(evt);
            }
        });

        st_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        st_Sc_Degree.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bachelor", "Master" }));

        add_Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_Btn.setForeground(new java.awt.Color(51, 0, 204));
        add_Btn.setText("Add");
        add_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_BtnActionPerformed(evt);
            }
        });

        prev_Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prev_Btn.setForeground(new java.awt.Color(51, 0, 204));
        prev_Btn.setText("<<");
        prev_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prev_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_BtnActionPerformed(evt);
            }
        });

        st_Semister.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        Email1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Email1.setForeground(new java.awt.Color(51, 0, 204));
        Email1.setText("Password");

        homeBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/homepage.png"))); // NOI18N
        homeBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(st_level, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(st_Semister, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(st_Specilize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(st_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(st_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(st_Email)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(st_Sc_Degree, 0, 176, Short.MAX_VALUE)
                                .addComponent(st_Type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(homeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(prev_Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next_Btn)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_Id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_Sc_Degree, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_Specilize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(st_Semister, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st_level, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prev_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_BtnActionPerformed
        // TODO add your handling code here:
        student_Next();
    }//GEN-LAST:event_next_BtnActionPerformed

    private void st_SpecilizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_SpecilizeActionPerformed
        // TODO add your handling code here:
        // لو تخصص الطالب غير الحاسب عدد المستويات بيكون
        // 8
        if (!st_Specilize.getSelectedItem().toString().equals("Computer Science")) {
            st_level.removeAllItems();
            for (int i = 1; i <= 8; i++) {
                st_level.addItem(i);
            }

        } else {
            st_level.removeAllItems();
            for (int i = 1; i <= 10; i++) {
                st_level.addItem(i);
            }
        }
    }//GEN-LAST:event_st_SpecilizeActionPerformed

    private void add_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_BtnActionPerformed
        // TODO add your handling code here:

        // PROCESS
        getStudentData();
    }//GEN-LAST:event_add_BtnActionPerformed

    private void prev_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_BtnActionPerformed
        // TODO add your handling code here:
        student_previous();
    }//GEN-LAST:event_prev_BtnActionPerformed

    private void homeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn1ActionPerformed
        // TODO add your handling code here:
        new adminHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtn1ActionPerformed
    public void getStudentData() {

        beans.Student student = new beans.Student();
        // INPUTS
        // get inputs from user
        String id = st_Id.getText();
        String name = st_Name.getText();
        String email = st_Email.getText();
        String pass = st_Pass.getText();
        String sc_Degree = st_Sc_Degree.getSelectedItem().toString();
        String st_type = st_Type.getSelectedItem().toString();
        String st_Spech = st_Specilize.getSelectedItem().toString();
        String level = st_level.getSelectedItem().toString();
        String Semister = st_Semister.getSelectedItem().toString();
        String error_Msg = "";

        if (!Manager.isCorrectData(id)) {
            error_Msg += "id";
        }
        if (!Manager.isCorrectData(name)) {
            error_Msg += ", name";
        }
        if (!Manager.isCorrectData(email)) {
            error_Msg += ", Email";
        }
        if (!Manager.isCorrectData(pass)) {
            error_Msg += ", Password";
        }
        // if now error 
        if (error_Msg.isEmpty()) {

            if (Manager.isNumeric(id)) {
                if (Manager.isStudentExist(Integer.parseInt(id))) {
                    JOptionPane.showMessageDialog(null, error_Msg);
                } else {
                    student.setId(Integer.parseInt(id));
                    student.setName(name);
                    student.setEmail(email);
                    student.setPass(pass);
                    student.setScientific_degree(sc_Degree);
                    student.setStudyType(st_type);
                    student.setSpecialization(st_Spech);
                    student.setLevel(level);
                    student.setSemister(Semister);

                    Manager.insertStudent(student);
                    JOptionPane.showMessageDialog(null, "Student Inserted sucessfully");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ID Must Be a Number .. !");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error In " + error_Msg);
        }

    }

    void setData(beans.Student student) {

        // set data of subject for this loged student
        st_Id.setText("" + student.getId());
        st_Name.setText(student.getName());
        st_Email.setText("" + student.getEmail());
        st_Pass.setText("" + student.getPass());
        st_Sc_Degree.addItem(student.getScientific_degree());
        st_Semister.addItem(student.getSemister());
        st_Specilize.addItem(student.getSpecialization());
        st_level.addItem(student.getLevel());
        st_Type.addItem(student.getStudyType());

    }

    public void student_Next() {

        if (!studentList.isEmpty()) {
            // increment index to get the student_Next record .. 
            index++;

            // check if index reache to the array List size this mean that we reach to the final record ... 
            if (index == studentList.size()) {
                // show message 
                JOptionPane.showMessageDialog(null, "You Reach to the final record !");
                // disable the student_Next button to don't be able to press student_Next again
                // reset index gain 
                index = studentList.size() - 1;
            } else {
                // set data of Order to lables
                setData(studentList.get(index));
            }
        } else {
            index = 0;
            JOptionPane.showMessageDialog(null, "No Data ... ");
        }
    }

    // داله للذهاب الي الريكورد السابق
    public void student_previous() {

        // decrement index by one to get the student_previous record
        if (!studentList.isEmpty()) {
            index--;
            if (index == -1) {
                // show message 
                JOptionPane.showMessageDialog(null, "You Reach to the First record !");
                // reset index 
                index = 0;
            } else {
                setData(studentList.get(index));
            }
        } else {
            JOptionPane.showMessageDialog(null, "No Data ...");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JButton add_Btn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton next_Btn;
    private javax.swing.JButton prev_Btn;
    private javax.swing.JTextField st_Email;
    private javax.swing.JTextField st_Id;
    private javax.swing.JTextField st_Name;
    private javax.swing.JTextField st_Pass;
    private javax.swing.JComboBox st_Sc_Degree;
    private javax.swing.JComboBox st_Semister;
    private javax.swing.JComboBox st_Specilize;
    private javax.swing.JComboBox st_Type;
    private javax.swing.JComboBox st_level;
    // End of variables declaration//GEN-END:variables
}
